Repository PagerDuty/backstage-plugin-backend, pull requests merged in 2024-07, with the labels that each got.

#63 feat: entity mapping persistence
  .gitattributes
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-3.8.2.cjs
  .yarnrc.yml
  migrations/20240527_init.js
  package.json
  src/apis/pagerduty.test.ts
  src/apis/pagerduty.ts
  src/db/PagerDutyBackendDatabase.ts
  src/db/index.ts
  src/plugin.ts
  src/run.ts
  src/service/router.test.ts
  src/service/router.ts
  src/service/standaloneServer.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#64 release: 0.7.0
  .gitattributes
  .yarn/releases/yarn-3.6.3.cjs
  .yarn/releases/yarn-3.8.2.cjs
  .yarnrc.yml
  migrations/20240527_init.js
  package.json
  src/apis/pagerduty.test.ts
  src/apis/pagerduty.ts
  src/db/PagerDutyBackendDatabase.ts
  src/db/index.ts
  src/plugin.ts
  src/run.ts
  src/service/router.test.ts
  src/service/router.ts
  src/service/standaloneServer.ts
  tsconfig.json
  yarn.lock
Labels: release

#66 fix: handle empty teams array to prevent TypeError
  src/service/router.ts
Labels: bug

#67 release: 0.7.1
  src/service/router.ts
Labels: release

#69 fix: ignore invalid integration keys when building entity reference dict
  src/service/router.test.ts
  src/service/router.ts
Labels: bug

#70 release: 0.7.2
  src/service/router.test.ts
  src/service/router.ts
Labels: release

#71 feat: add support for multiple accounts
  config.d.ts
  migrations/20240710_add_account_column.js
  package.json
  src/apis/pagerduty.test.ts
  src/apis/pagerduty.ts
  src/auth/auth.ts
  src/db/PagerDutyBackendDatabase.ts
  src/service/router.ts
  yarn.lock
Labels: enhancement

#72 release: 0.8.0
  config.d.ts
  migrations/20240710_add_account_column.js
  package.json
  src/apis/pagerduty.test.ts
  src/apis/pagerduty.ts
  src/auth/auth.ts
  src/db/PagerDutyBackendDatabase.ts
  src/service/router.ts
  yarn.lock
Labels: release

#76 release: 0.8.1
  package.json
  yarn.lock
Labels: release

#77 chore: refactor JSON.parse usage on unsafe code
  src/service/router.ts
Labels: enhancement

#78 release: 0.8.2
  src/service/router.ts
Labels: release

#81 feat: service dependency sync
  migrations/20240722_add_settings_table.js
  package.json
  src/apis/pagerduty.ts
  src/db/PagerDutyBackendDatabase.ts
  src/service/router.test.ts
  src/service/router.ts
  yarn.lock
Labels: enhancement

#82 release: 0.9.0
  migrations/20240722_add_settings_table.js
  package.json
  src/apis/pagerduty.ts
  src/db/PagerDutyBackendDatabase.ts
  src/service/router.test.ts
  src/service/router.ts
  yarn.lock
Labels: release
